package com.chae.apiservice.message.enumeration;

public enum MessageTypeEnumeration {
    VERIFY_AUCTION_KAKAO_MESSAGE,
    AUCTION_BIDDING_KAKAO_MESSAGE,
    AUCTION_BID_FAILED_KAKAO_MESSAGE,
    AUCTION_ACCEPTED_PUSH_MESSAGE,
    AUCTION_STARTED_PUSH_MESSAGE;
}
